baseURL = "https://blog.dedigitaletopschool.nl/"
languageCode = "nl-nl"
title = "De Digitale Topschool blog"
theme = 'base16'

[params]
  description = 'Online onderwijs voor kinderen op de basisschool met talent voor leren.'
